# Đổi phím Prefix từ Ctrl+b sang Ctrl+a (giống Primeagen hay dùng)
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Chia màn hình bằng | và -
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Làm mới cấu hình tmux bằng 'r'
unbind r
bind r source-file ~/.tmux.conf

# Di chuyển giữa các khung (panes) bằng phím nvim (h,j,k,l)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# Cho phép dùng chuột
set -g mouse on

# Danh sách plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' # Di chuyển mượt giữa nvim và tmux
set -g @plugin 'jimeh/tmux-themepack' # Giao diện màu sắc
set -g @themepack 'powerline/default/cyan'
# Hỗ trợ hiển thị màu sắc 256 và icon chuẩn
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Khởi tạo TPM (luôn để ở cuối file)
run '~/.tmux/plugins/tpm/tpm'
